
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-06
owner: ucsb-cs156-f24
repo_name: team02-f24-06
pull_requests: [{"author":{"id":"MDQ6VXNlcjYzNTg4NzIx","is_bot":false,"login":"SexyCarrots","name":"Xinghan Yang"},"headRefName":"sexycarrots-dev","number":90,"title":"Form Component for UCSBDiningCommonsMenuItem plus tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-06/pull/90"},{"author":{"id":"MDQ6VXNlcjU3NDYyMjQz","is_bot":false,"login":"vprchlik","name":"Victor Prchlik"},"headRefName":"vp-Articles-table","number":89,"title":"vp articles table component","url":"https://github.com/ucsb-cs156-f24/team02-f24-06/pull/89"},{"author":{"id":"MDQ6VXNlcjU3NDYyMjQz","is_bot":false,"login":"vprchlik","name":"Victor Prchlik"},"headRefName":"vp-Articles-components","number":87,"title":"vp - Articles, added form component","url":"https://github.com/ucsb-cs156-f24/team02-f24-06/pull/87"}]
