
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-06
owner: ucsb-cs156-f24
repo_name: team02-f24-06
pull_requests: [{"author":{"id":"U_kgDOB2_WkA","is_bot":false,"login":"skanda-vasishta","name":""},"headRefName":"sv-menuitemreview-index","number":110,"title":"hopefully done w menu item review edit page, resolves issue #42","url":"https://github.com/ucsb-cs156-f24/team02-f24-06/pull/110"},{"author":{"id":"MDQ6VXNlcjU1MTYzOTcx","is_bot":false,"login":"ELEXG","name":"Edward Garcia"},"headRefName":"eg-HelpRequest-EditPage","number":109,"title":"eg - adds help request edit page","url":"https://github.com/ucsb-cs156-f24/team02-f24-06/pull/109"},{"author":{"id":"MDQ6VXNlcjU3NDYyMjQz","is_bot":false,"login":"vprchlik","name":"Victor Prchlik"},"headRefName":"vp-Articles-edit","number":105,"title":"vp - Added edit page for Articles","url":"https://github.com/ucsb-cs156-f24/team02-f24-06/pull/105"}]
