
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-06
owner: ucsb-cs156-f24
repo_name: team02-f24-06
pull_requests: [{"author":{"id":"MDQ6VXNlcjU1MTYzOTcx","is_bot":false,"login":"ELEXG","name":"Edward Garcia"},"headRefName":"eg-team01","number":65,"title":"eg - team01 files for HelpRequest","url":"https://github.com/ucsb-cs156-f24/team02-f24-06/pull/65"},{"author":{"id":"MDQ6VXNlcjQzMzk0Njg0","is_bot":false,"login":"chriswlai","name":"Christopher Lai"},"headRefName":"cl-backend","number":64,"title":"Add backend files for UCSB Organizations","url":"https://github.com/ucsb-cs156-f24/team02-f24-06/pull/64"}]
