
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-06
owner: ucsb-cs156-f24
repo_name: team02-f24-06
pull_requests: [{"author":{"id":"U_kgDOBs-ReA","is_bot":false,"login":"michaelljiang","name":"Michael Jiang"},"headRefName":"mj-recreq-form","number":69,"title":"MJ - Recommendation Request Form","url":"https://github.com/ucsb-cs156-f24/team02-f24-06/pull/69"},{"author":{"id":"MDQ6VXNlcjQzMzk0Njg0","is_bot":false,"login":"chriswlai","name":"Christopher Lai"},"headRefName":"cl-fixtures","number":67,"title":"add fixtures for UCSBOrganization","url":"https://github.com/ucsb-cs156-f24/team02-f24-06/pull/67"}]
